### ISSUE TITLE
json: cannot unmarshal string into Go struct field clientOpts.tls_required of type bool

### ISSUE THREAD

**Issue by haidinhtuan** [tyagihas/scala_nats#5]
When I used the client follwing this example:

```
var opts : Properties = new Properties
opts.put("servers", "nats://user1:pass1@server1,nats://user1:pass1@server2:4243");
var conn = Conn.connect(opts)

println("Publishing...")
conn.publish("hello", "world")
```

The broker keeps complaining "json: cannot unmarshal string into Go struct field clientOpts.tls_required of type bool"

**Comment by nguyen1994** [comment]
the same error. please how to fix them .

**Comment by tyagihas** [comment]
Just pushed the latest code. It should be available through maven within a day.

**Comment by ashewnarain** [comment]
Hello @tyagihas, I have given this a try, (v0.4.0) and noticing a versioning issue on the **Conn** class. Here's a screenshot - 
![image](https://user-images.githubusercontent.com/6341053/87692203-7b210600-c759-11ea-87ea-efb14941bf34.png)

**Comment by tyagihas** [comment]
What version of scala are you using?

**Comment by ashewnarain** [comment]
@tyagihas - our project is on scala version 2.11.12. Do you know if it's backward compatible to this version or if the changes made require the latest 2.13.3?

**Comment by tyagihas** [comment]
Can you try using JDK14 ? scala_nats has dependency on my java_nats implementation which is compiled with JDK 14.

**Comment by ashewnarain** [comment]
Unfortunately the project we're on is using JDK 8 due to some internal dependencies.

**Comment by tyagihas** [comment]
If that's the case, you can download and add both source code of java_nats and scala_nats to your project. java_nats doesn't have any dependency on other external libraries so it should be easy to compile it.

**Comment by tyagihas** [comment]
I will close this for now. Please reopen it if you still have an issue.
